name: ShopRotation
version: 1.0.0
api-version: 1.19
authors: [Hakuyamu, NYC_1809]
main: de.skycave.shoprotation.ShopRotation
depend:
  - SkyBeeCore

commands:
  shoprotation:
    aliases: [srotation]
    permission: skycave.shoprotation.admin

